[package]
name = "mkpdf"
version = "0.3.5"
edition = "2021"

[dependencies]
image = "0.25.1"
jpeg-to-pdf = "0.2.3"
anyhow = "1.0.86"
debug_print = "1.0.0"
regex = "1.10.4"
my_image = { path = "../lib/my_image", version = "0.1.0" }